
ORY_NET_PROJECT_ID=bcEXAMPLE5b-8301-4b8a-96f8-daEXAMPLE4b
ORY_NET_SLUG=cranky-wu-svEXAMPLEgi
ORY_NET_API_ENDPOINT=https://cranky-wu-svEXAMPLEgi.projects.oryapis.com

ORY_API_KEY=ory_pat_VmEXAMPLE9jGEXAMPLEDJMsEXAMPLE06Q

